# Generated by Django 5.0.6 on 2024-07-09 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_customer_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_id',
        ),
    ]
