# Generated by Django 5.0.6 on 2024-07-09 13:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_serviceprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('catagory', models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('cleaning', 'Cleaning'), ('gardening', 'Gardening')], max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_calls', to='service.customer')),
            ],
        ),
    ]
