# Generated by Django 5.0.6 on 2024-07-10 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_servicecall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecall',
            old_name='catagory',
            new_name='category',
        ),
    ]
