# Generated by Django 5.0.6 on 2024-07-10 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_rename_catagory_servicecall_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='servicecall',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='service_provider_id',
        ),
    ]
