# Generated by Django 5.0.6 on 2024-07-10 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_remove_customer_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Cost in rupees', max_digits=10)),
                ('time_taken', models.DecimalField(decimal_places=2, help_text='Time taken in hours', max_digits=5)),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_calls', to='service.servicecall')),
                ('service_provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_providers', to='service.serviceprovider')),
            ],
        ),
    ]
