# Generated by Django 5.0.6 on 2024-07-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_responsecall_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsecall',
            name='status',
        ),
    ]
