# Generated by Django 5.0.6 on 2024-07-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_remove_responsecall_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsecall',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
