# Generated by Django 5.0.6 on 2024-07-11 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_remove_responsecall_status_servicecall_responded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='servicecall',
            name='responded',
        ),
    ]
