# Generated by Django 5.0.6 on 2024-07-11 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_remove_customer_address_remove_servicecall_responded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accepted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.CharField(max_length=15)),
                ('customer_name', models.CharField(max_length=255)),
                ('service_provider_contact', models.CharField(max_length=15)),
                ('service_provider_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('category', models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('cleaning', 'Cleaning'), ('gardening', 'Gardening')], max_length=50)),
                ('problem', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, help_text='Cost in rupees', max_digits=10)),
                ('time_taken', models.DecimalField(decimal_places=2, help_text='Time taken in hours', max_digits=5)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.customer')),
                ('service_provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.serviceprovider')),
            ],
        ),
    ]
