# Generated by Django 5.0.6 on 2024-07-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='accepted',
            name='payment_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accepted',
            name='service_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accepted',
            name='venue_reached',
            field=models.BooleanField(default=False),
        ),
    ]
