# Generated by Django 5.0.6 on 2024-07-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_accepted_payment_received_accepted_service_provided_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accepted',
            name='service_approval_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accepted',
            name='service_approval_service_provider',
            field=models.BooleanField(default=False),
        ),
    ]
