# Generated by Django 5.0.6 on 2024-07-11 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_accepted_payment_approval_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accepted',
            old_name='payment_approval_service_porvider',
            new_name='payment_approval_service_provider',
        ),
    ]
